name: Run Validation Notebook

on:
  push:
    branches:
      - main

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    env:
      COMPANIES_HOUSE_API_KEY: ${{ secrets.COMPANIES_HOUSE_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install jupyter nbconvert

      - name: Run notebook
        run: |
          jupyter nbconvert --execute --inplace --to notebook CluedIn_Harshith_Task.ipynb
